version: '3'
services:
  firebase-auth-service:
    build: .
    container_name: 'firebase-auth-service'
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./service-account:/service-account
